#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    # Update GTK3 IM modules cache
    if command -v gtk-query-immodules-3.0 >/dev/null 2>&1; then
        gtk-query-immodules-3.0 --update-cache || true
    fi
    ldconfig || true
fi

exit 0
