#!/usr/bin/env bash
# Generate installer/wix/generated/guids.wxi from unim-tsf/src/globals.rs.
# Single source of truth: Rust const → WiX preprocessor variables.
#
# Run from repo root:  bash installer/wix/gen-guids.sh
# CI verifies no drift via `git diff --exit-code installer/wix/generated/`.

set -euo pipefail

cd "$(dirname "$0")/../.."

SRC="unim-tsf/src/globals.rs"
OUT="installer/wix/generated/guids.wxi"

if [[ ! -f "$SRC" ]]; then
  echo "ERROR: $SRC not found" >&2
  exit 1
fi

# Extract u128 hex literal for a const name from globals.rs.
# Handles single-line and broken-line definitions.
extract() {
  local name="$1"
  # Join continuation lines, then match.
  awk -v n="$name" '
    /pub const / { buf=$0; while ($0 !~ /;/) { getline; buf = buf " " $0 } print buf }
  ' "$SRC" | grep -E "pub const ${name}\s*:" | head -1 | \
    sed -E 's/.*from_u128\(0x([0-9A-Fa-f_]+)\).*/\1/' | tr -d '_'
}

format_guid() {
  local hex="$1"
  if [[ ${#hex} -ne 32 ]]; then
    echo "ERROR: hex must be 32 chars, got ${#hex}: $hex" >&2
    exit 1
  fi
  printf '%s-%s-%s-%s-%s\n' \
    "${hex:0:8}" "${hex:8:4}" "${hex:12:4}" "${hex:16:4}" "${hex:20:12}"
}

CLSID=$(format_guid "$(extract UNIM_CLSID)")
PROFILE=$(format_guid "$(extract UNIM_PROFILE_GUID)")
DISP_INPUT=$(format_guid "$(extract UNIM_DISPLAY_ATTR_INPUT)")
DISP_CONVERTED=$(format_guid "$(extract UNIM_DISPLAY_ATTR_CONVERTED)")
LANGID_HEX=$(grep -E '^pub const UNIM_LANGID_KOREAN' "$SRC" | sed -E 's/.*0x([0-9A-Fa-f]+).*/\1/')

VERSION=$(grep -E '^version *= *"' Cargo.toml | head -1 | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
if [[ -z "$VERSION" ]]; then
  echo "ERROR: workspace version not found in Cargo.toml" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by installer/wix/gen-guids.sh from unim-tsf/src/globals.rs.
  DO NOT EDIT BY HAND. Run the script to refresh after editing globals.rs.
  CI verifies drift by running git diff over installer/wix/generated/.
-->
<Include>
  <?define UnimClsid = "{${CLSID}}" ?>
  <?define UnimProfileGuid = "{${PROFILE}}" ?>
  <?define UnimDisplayAttrInput = "{${DISP_INPUT}}" ?>
  <?define UnimDisplayAttrConverted = "{${DISP_CONVERTED}}" ?>
  <?define UnimLangIdHex = "0x${LANGID_HEX}" ?>
  <?define UnimLangIdHexPadded = "0x0000${LANGID_HEX}" ?>
  <?define UnimVersion = "${VERSION}" ?>
</Include>
EOF

echo "wrote $OUT"
echo "  CLSID       = {${CLSID}}"
echo "  Profile     = {${PROFILE}}"
echo "  LangID      = 0x${LANGID_HEX}"
echo "  Version     = ${VERSION}"
