# vim: set sts=4 expandtab:
IM_CONFIG_SHORT="$(gettext "activate UNIM (A Korean Input Method)")"

IM_CONFIG_LONG="$(gettext "UNIM (A Korean Input Method)
  * Essential package: unim (core engine & daemons)
 * Language specific input conversion support:
   * Korean (2-bul, 3-bul, etc.)
 * Application platform support:
   * Wayland: unim-wayland (via unim-daemon)
   * X11/XIM/Clutter: unim-xim (via unim-daemon)
   * GTK3/4: libim-unim.so
   * Qt5/6: libunim.so")"

package_auto () {
    package_status unim
}

package_menu () {
    package_status unim || package_status unim-gtk || package_status unim-qt
}
