# vim: set sts=4 expandtab:
IM_CONFIG_SHORT="$(gettext "activate UNIM (A Korean Input Method)")"

IM_CONFIG_LONG="$(gettext "UNIM (A Korean Input Method)
 * Required for all: unim-daemon
 * Language specific input conversion support:
   * Korean (2-bul, 3-bul)
 * Application platform support:
   * Wayland: unim-wayland (via unim-daemon)
   * X11/XIM: unim-xim (via unim-daemon)
   * GTK3: libim-unim.so
   * Qt5/6: libunimplatforminputcontextplugin.so")"

package_auto () {
    package_status unim-core
}

package_menu () {
    package_status unim-core
}
