[package]
name = "unim"
version = "0.0.1"
edition = "2021"

[dependencies]
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
dirs = "5.0"
chrono = "0.4"
x11 = "2.18.2"
libc = "0.2"

[lib]
name = "unim"
path = "src/lib.rs"

[workspace]
members = [
    "unim-cli",
    "unim-capi",
    "unim-config",
    "unim-frontends/xim",
    "unim-frontends/wayland",
    "unim-daemon",
    "unim-gui",
    "unim-dbus",
    "unim-test-wayland",
]
resolver = "2"
