[package]
name = "unim-wayland"
version = "0.0.1"
edition = "2021"
description = "UNIM Wayland Input Method Frontend"

[[bin]]
name = "unim-wayland"
path = "src/main.rs"

[dependencies]
unim = { path = "../.." }
unim-dbus = { path = "../../unim-dbus" }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["staging", "unstable", "client"] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
xkbcommon = { version = "0.8", features = ["wayland"] }
tokio = { version = "1", features = ["rt", "sync"] }
zbus = { version = "4", default-features = false, features = ["tokio"] }
mio = { version = "1", features = ["os-poll"] }
nix = { version = "0.29", features = ["time", "fs", "mman"] }
tiny-skia = "0.11"
cosmic-text = { version = "0.12", default-features = false, features = ["std", "swash"] }
memmap2 = "0.9"
futures-util = "0.3"
