[package]
name = "unim-wayland"
version = "0.1.0"
edition = "2021"
description = "UNIM Wayland Input Method Frontend"

[[bin]]
name = "unim-wayland"
path = "src/main.rs"

[dependencies]
unim = { path = "../.." }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["staging", "unstable", "client"] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
log = "0.4"
env_logger = "0.11"
