[package]
name = "unim-test-wayland"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
# Wayland
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
smithay-client-toolkit = { version = "0.19", default-features = false, features = ["calloop", "xkbcommon"] }

# Event Loop
calloop = "0.13"

# Keyboard handling
xkbcommon = { version = "0.7", features = ["wayland"] }

# Rendering
tiny-skia = "0.11"
cosmic-text = { version = "0.12", default-features = false, features = ["std", "swash"] }

# Logging
unim = { path = "../.." }

# Auto test
unim-dbus = { path = "../../unim-dbus" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
calloop-wayland-source = "0.3.0"
