[package]
name = "unim-daemon"
version = "0.0.1"
edition = "2021"
description = "UNIM Input Method Daemon"

[[bin]]
name = "unim-daemon"
path = "src/main.rs"

[dependencies]
unim = { path = ".." }
unim-dbus = { path = "../unim-dbus" }
log = "0.4"
env_logger = "0.11"
daemonize = "0.5"
ctrlc = "3.4"
dirs = "5.0"
which = "6.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
zbus = { version = "4", default-features = false, features = ["tokio"] }
