#!/usr/bin/env python3
"""Generate src/emoji/data.rs from Unicode emoji-test.txt.

Produces a flat list of (emoji_str, category_idx, en_name, subgroup).
Filters out the Component group and skin-tone variants to match the
Windows 11 emoji panel scope (~1900 base emojis).

PR #1 변경 (이모지 전면 개선):
- 9 카테고리 → 8 카테고리 (People → Smileys 흡수, id="SmileysPeople")
- Flags ko 라벨: "깃발" → "국기"
- Smileys ko 라벨: "표정" → "표정·인물" (인덱스 0, id "SmileysPeople")
- 출력 경로 변경: src/hangul/emoji_data.rs → src/emoji/data.rs
- "Recent" 카테고리는 데이터에 들어가지 않고 runtime 동적 (yaml 영속화).

Run from repo root:
    python3 tools/gen_emoji.py
"""
import re
from pathlib import Path

SRC = Path("/usr/share/unicode/emoji/emoji-test.txt")
OUT = Path(__file__).resolve().parent.parent / "src/emoji/data.rs"

# 8 메이저 카테고리. (id, 한국어, 영어)
# People & Body 그룹은 SmileysPeople 로 흡수된다 (사용자 결정 #5).
GROUP_TO_CAT = {
    "Smileys & Emotion": ("SmileysPeople", "표정·인물", "Smileys & people"),
    "People & Body":     ("SmileysPeople", "표정·인물", "Smileys & people"),
    "Animals & Nature":  ("Animals",       "동물·자연", "Animals & nature"),
    "Food & Drink":      ("Food",          "음식·음료", "Food & drink"),
    "Activities":        ("Activities",    "활동",      "Activities"),
    "Travel & Places":   ("Travel",        "여행·장소", "Travel & places"),
    "Objects":           ("Objects",       "사물",      "Objects"),
    "Symbols":           ("Symbols",       "기호",      "Symbols"),
    "Flags":             ("Flags",         "국기",      "Flags"),
}
# CATEGORIES 배열 출력 순서 (사용자 결정 #12, Recent 제외).
# 인덱스 0 = SmileysPeople ... 인덱스 7 = Flags.
CAT_ORDER_IDS = [
    "SmileysPeople", "Animals", "Food", "Activities",
    "Travel", "Objects", "Symbols", "Flags",
]
# emoji-test.txt 의 그룹 순회 순서 (Smileys & Emotion 다음 People & Body 가 SmileysPeople 에 누적).
GROUP_ORDER = [
    "Smileys & Emotion", "People & Body", "Animals & Nature",
    "Food & Drink", "Activities", "Travel & Places",
    "Objects", "Symbols", "Flags",
]

SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}

def parse():
    group = None
    subgroup = None
    with SRC.open(encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line:
                continue
            if line.startswith('# group:'):
                group = line[len('# group:'):].strip()
                continue
            if line.startswith('# subgroup:'):
                subgroup = line[len('# subgroup:'):].strip()
                continue
            if line.startswith('#'):
                continue
            m = re.match(r'^([0-9A-Fa-f ]+?)\s*;\s*(\S+)\s*#\s*(\S+)\s+(?:E[\d.]+\s+)?(.+)$', line)
            if not m:
                continue
            codes_str, status, emoji_str, name = m.groups()
            if status != 'fully-qualified':
                continue
            codes = [int(c, 16) for c in codes_str.strip().split()]
            if group == 'Component':
                continue
            if any(c in SKIN_TONES for c in codes):
                continue
            if 'skin tone' in name.lower():
                continue
            yield (emoji_str, codes, group, subgroup, name)

def main():
    entries = list(parse())
    print(f"Parsed {len(entries)} base emojis")

    # 카테고리별 emoji 누적. People & Body 와 Smileys & Emotion 은 같은 cat_id
    # ("SmileysPeople") 로 합쳐진다 — emoji-test.txt 그룹 순회 순서에 따라
    # Smileys 가 먼저, People 이 뒤에 누적된다.
    by_cat: dict[str, list] = {cat_id: [] for cat_id in CAT_ORDER_IDS}
    # 출처별 누적 (디버그/통계용)
    by_source_group: dict[str, int] = {}
    for em, codes, group, subgroup, name in entries:
        if group not in GROUP_TO_CAT:
            continue
        cat_id = GROUP_TO_CAT[group][0]
        by_cat.setdefault(cat_id, []).append((em, subgroup, name))
        by_source_group[group] = by_source_group.get(group, 0) + 1

    # 출력 순서대로 정렬하여 데이터 블록 생성
    cat_id_to_idx = {cat_id: i for i, cat_id in enumerate(CAT_ORDER_IDS)}
    # 카테고리당 한 번씩만 메타 (id, ko, en) 추출 — GROUP_TO_CAT 의 첫 매핑.
    cat_meta: dict[str, tuple[str, str]] = {}
    for group_name in GROUP_ORDER:
        cat_id, ko, en = GROUP_TO_CAT[group_name]
        cat_meta.setdefault(cat_id, (ko, en))

    out = []
    out.append("// AUTO-GENERATED by tools/gen_emoji.py from Unicode emoji-test.txt (15.0).")
    out.append("// DO NOT EDIT MANUALLY. Regenerate via `python3 tools/gen_emoji.py`.")
    out.append("//")
    out.append("// Source : /usr/share/unicode/emoji/emoji-test.txt (Unicode 15.0, 2023-06-05)")
    out.append("// Filter : fully-qualified base emojis only; Component group and skin-tone")
    out.append("//          variants excluded (matches Windows 11 emoji panel scope).")
    out.append("//")
    out.append("// PR #1 (emoji overhaul) — 8 카테고리 (People → SmileysPeople 흡수).")
    out.append("// 'Recent' 카테고리는 runtime 동적이므로 본 데이터에 포함되지 않는다.")
    out.append("")
    out.append("/// 카테고리 정보 (id, 한국어 표시명, 영어 표시명)")
    out.append("#[derive(Debug, Clone, Copy)]")
    out.append("pub struct EmojiCategoryInfo {")
    out.append("    pub id: &'static str,")
    out.append("    pub ko: &'static str,")
    out.append("    pub en: &'static str,")
    out.append("}")
    out.append("")
    out.append("/// 이모지 데이터 카테고리 (8개). 'Recent' 는 runtime 동적이므로 별도 관리.")
    out.append("#[rustfmt::skip]")
    out.append("pub static CATEGORIES: &[EmojiCategoryInfo] = &[")
    for cat_id in CAT_ORDER_IDS:
        ko, en = cat_meta[cat_id]
        out.append(f"    EmojiCategoryInfo {{ id: \"{cat_id}\", ko: \"{ko}\", en: \"{en}\" }},")
    out.append("];")
    out.append("")
    out.append("/// 이모지 1건의 메타데이터.")
    out.append("#[derive(Debug, Clone, Copy)]")
    out.append("pub struct EmojiDatum {")
    out.append("    pub emoji:    &'static str,")
    out.append("    pub cat_idx:  u8,")
    out.append("    pub en_name:  &'static str,")
    out.append("    pub subgroup: &'static str,")
    out.append("}")
    out.append("")
    out.append("#[rustfmt::skip]")
    out.append("pub static EMOJIS: &[EmojiDatum] = &[")
    total = 0
    cat_counts = {}
    for cat_id in CAT_ORDER_IDS:
        items = by_cat.get(cat_id, [])
        cat_counts[cat_id] = len(items)
        out.append(f"    // === {cat_id} ({len(items)}) ===")
        for em, subgroup, name in items:
            safe_name = name.replace('\\', r'\\').replace('"', r'\"')
            safe_sub  = subgroup.replace('\\', r'\\').replace('"', r'\"')
            out.append(
                f"    EmojiDatum {{ emoji: \"{em}\", cat_idx: {cat_id_to_idx[cat_id]}, "
                f"en_name: \"{safe_name}\", subgroup: \"{safe_sub}\" }},"
            )
            total += 1
    out.append("];")
    out.append("")
    out.append(f"pub const TOTAL_EMOJIS: usize = {total};")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print(f"Wrote {OUT} ({total} emojis)")
    print("Per-category counts:")
    for k, v in cat_counts.items():
        print(f"  {k}: {v}")
    print("Per-source-group counts (Smileys & People → 합쳐짐):")
    for k, v in by_source_group.items():
        print(f"  {k}: {v}")

if __name__ == '__main__':
    main()
