#!/usr/bin/env python3
"""Generate src/hangul/emoji_data.rs from Unicode emoji-test.txt.

Produces a flat list of (emoji_str, category_idx, en_name, subgroup).
Filters out the Component group and skin-tone variants to match the
Windows 11 emoji panel scope (~1900 base emojis).

Run from repo root:
    python3 tools/gen_emoji.py
"""
import re
from pathlib import Path

SRC = Path("/usr/share/unicode/emoji/emoji-test.txt")
OUT = Path(__file__).resolve().parent.parent / "src/hangul/emoji_data.rs"

# 9 메이저 카테고리. (id, 한국어, 영어)
GROUP_TO_CAT = {
    "Smileys & Emotion": ("Smileys",    "표정",      "Smileys & emotion"),
    "People & Body":     ("People",     "사람",      "People & body"),
    "Animals & Nature":  ("Animals",    "동물·자연", "Animals & nature"),
    "Food & Drink":      ("Food",       "음식·음료", "Food & drink"),
    "Travel & Places":   ("Travel",     "여행·장소", "Travel & places"),
    "Activities":        ("Activities", "활동",      "Activities"),
    "Objects":           ("Objects",    "사물",      "Objects"),
    "Symbols":           ("Symbols",    "기호",      "Symbols"),
    "Flags":             ("Flags",      "깃발",      "Flags"),
}
CAT_ORDER = [
    "Smileys & Emotion","People & Body","Animals & Nature",
    "Food & Drink","Travel & Places","Activities",
    "Objects","Symbols","Flags",
]

SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}

def parse():
    group = None
    subgroup = None
    with SRC.open(encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line:
                continue
            if line.startswith('# group:'):
                group = line[len('# group:'):].strip()
                continue
            if line.startswith('# subgroup:'):
                subgroup = line[len('# subgroup:'):].strip()
                continue
            if line.startswith('#'):
                continue
            m = re.match(r'^([0-9A-Fa-f ]+?)\s*;\s*(\S+)\s*#\s*(\S+)\s+(?:E[\d.]+\s+)?(.+)$', line)
            if not m:
                continue
            codes_str, status, emoji_str, name = m.groups()
            if status != 'fully-qualified':
                continue
            codes = [int(c, 16) for c in codes_str.strip().split()]
            if group == 'Component':
                continue
            if any(c in SKIN_TONES for c in codes):
                continue
            if 'skin tone' in name.lower():
                continue
            yield (emoji_str, codes, group, subgroup, name)

def main():
    entries = list(parse())
    print(f"Parsed {len(entries)} base emojis")

    by_cat: dict[str, list] = {}
    for em, codes, group, subgroup, name in entries:
        if group not in GROUP_TO_CAT:
            continue
        cat_id = GROUP_TO_CAT[group][0]
        by_cat.setdefault(cat_id, []).append((em, subgroup, name))

    cat_id_to_idx = {GROUP_TO_CAT[g][0]: i for i, g in enumerate(CAT_ORDER)}

    out = []
    out.append("// AUTO-GENERATED by tools/gen_emoji.py from Unicode emoji-test.txt (15.0).")
    out.append("// DO NOT EDIT MANUALLY. Regenerate via `python3 tools/gen_emoji.py`.")
    out.append("//")
    out.append("// Source : /usr/share/unicode/emoji/emoji-test.txt (Unicode 15.0, 2023-06-05)")
    out.append("// Filter : fully-qualified base emojis only; Component group and skin-tone")
    out.append("//          variants excluded (matches Windows 11 emoji panel scope).")
    out.append("")
    out.append("/// 카테고리 정보 (id, 한국어 표시명, 영어 표시명)")
    out.append("#[derive(Debug, Clone, Copy)]")
    out.append("pub struct EmojiCategoryInfo {")
    out.append("    pub id: &'static str,")
    out.append("    pub ko: &'static str,")
    out.append("    pub en: &'static str,")
    out.append("}")
    out.append("")
    out.append("/// Windows 11 emoji panel과 매칭되는 9개 메이저 카테고리.")
    out.append("pub static CATEGORIES: &[EmojiCategoryInfo] = &[")
    for g in CAT_ORDER:
        cat_id, ko, en = GROUP_TO_CAT[g]
        out.append(f"    EmojiCategoryInfo {{ id: \"{cat_id}\", ko: \"{ko}\", en: \"{en}\" }},")
    out.append("];")
    out.append("")
    out.append("/// 이모지 1건의 메타데이터.")
    out.append("#[derive(Debug, Clone, Copy)]")
    out.append("pub struct EmojiDatum {")
    out.append("    pub emoji:    &'static str,")
    out.append("    pub cat_idx:  u8,")
    out.append("    pub en_name:  &'static str,")
    out.append("    pub subgroup: &'static str,")
    out.append("}")
    out.append("")
    out.append("pub static EMOJIS: &[EmojiDatum] = &[")
    total = 0
    cat_counts = {}
    for group_name in CAT_ORDER:
        cat_id = GROUP_TO_CAT[group_name][0]
        items = by_cat.get(cat_id, [])
        cat_counts[cat_id] = len(items)
        out.append(f"    // === {cat_id} ({len(items)}) ===")
        for em, subgroup, name in items:
            safe_name = name.replace('\\', r'\\').replace('"', r'\"')
            safe_sub  = subgroup.replace('\\', r'\\').replace('"', r'\"')
            out.append(
                f"    EmojiDatum {{ emoji: \"{em}\", cat_idx: {cat_id_to_idx[cat_id]}, "
                f"en_name: \"{safe_name}\", subgroup: \"{safe_sub}\" }},"
            )
            total += 1
    out.append("];")
    out.append("")
    out.append(f"pub const TOTAL_EMOJIS: usize = {total};")
    out.append("")

    OUT.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print(f"Wrote {OUT} ({total} emojis)")
    print("Per-category counts:")
    for k, v in cat_counts.items():
        print(f"  {k}: {v}")

if __name__ == '__main__':
    main()
